//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bank()
        {
            this.salary_slip = new HashSet<salary_slip>();
        }
    
        public long Account_no { get; set; }
        public string Account_HName { get; set; }
        public string ifsc_code { get; set; }
        public Nullable<long> branch_code { get; set; }
        public Nullable<int> balance { get; set; }
        public string pan_card { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salary_slip> salary_slip { get; set; }
    }
}
