//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTestProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class empManagementEntities : DbContext
    {
        public empManagementEntities()
            : base("name=empManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<salary_slip> salary_slips { get; set; }
        public virtual DbSet<timesheet> timesheets { get; set; }
    
        public virtual ObjectResult<slip_Result> slip(Nullable<int> emp_id)
        {
            var emp_idParameter = emp_id.HasValue ?
                new ObjectParameter("emp_id", emp_id) :
                new ObjectParameter("emp_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<slip_Result>("slip", emp_idParameter);
        }
    }
}
