//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salary()
        {
            this.salary_slip = new HashSet<salary_slip>();
        }
    
        public int salary_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> Basic_pay { get; set; }
        public Nullable<int> House_rent { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<int> Provident_fund { get; set; }
        public Nullable<int> Esi { get; set; }
        public Nullable<int> Prof_Tax { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salary_slip> salary_slip { get; set; }
    }
}
