//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary_slip
    {
        public int sal_slip_id { get; set; }
        public Nullable<long> Account_no { get; set; }
        public Nullable<int> salary_id { get; set; }
        public Nullable<System.DateTime> sal_date { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual salary salary { get; set; }
    }
}
