//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet
    {
        public int sheet_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> attendance_id { get; set; }
    
        public virtual attendance attendance { get; set; }
        public virtual employee employee { get; set; }
    }
}
